### ISSUE TITLE
Respuesta equivocada en uno de los puntos del examen

### ISSUE THREAD

**Issue by jgomezbau** [romandescotte/sailing-quiz#1]
¿En que categoría cae un velero navegando a motor con las velas izadas?

BUQUE A MOTOR es la respuesta correcta. Tiene como correcta BUQUE A VELA,.

En el contexto del RIPA, un velero que navega a motor con las velas izadas se considera una embarcación de propulsión mecánica. [Esto se debe a que, según el RIPA, cualquier embarcación que esté utilizando su motor, independientemente de si tiene las velas izadas o no, se clasifica como una embarcación de propulsión mecánica.

**Comment by romandescotte** [comment]
Resuelto en 1c0cd2d. Gracias por el aporte @jgomezbau!
